#!/usr/bin/env bash
# shared helpers for warp-pool
set -euo pipefail

DATA_DIR="${DATA_DIR:-/data}"
INSTANCE_PORT_BASE="${INSTANCE_PORT_BASE:-11000}"
MTU="${MTU:-1280}"
ENDPOINT_IP="${ENDPOINT_IP:-}"
SCRIPTS_DIR="${SCRIPTS_DIR:-/opt/warp-pool/scripts}"
PID_DIR="${PID_DIR:-/run/warp-pool}"

log() { echo "==> [warp-pool] $*"; }
err() { echo "==> [warp-pool][ERROR] $*" >&2; }

instance_dir() {
  echo "${DATA_DIR}/instances/$1"
}

instance_port() {
  local id="$1"
  echo $((INSTANCE_PORT_BASE + id))
}

ensure_dirs() {
  local id="$1"
  mkdir -p "$(instance_dir "$id")" "${DATA_DIR}/state" "${PID_DIR}"
}

# Sanitize wgcf profile for wireproxy (IPv4-focused, MTU, keepalive, endpoint)
sanitize_wgconf() {
  local conf="$1"
  local tmp
  tmp="$(mktemp)"
  local ipv4
  ipv4="$(grep -E '^Address' "$conf" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}' | head -n1 || true)"

  # drop noisy / dual-stack lines we rewrite
  grep -v -E '^(Address|AllowedIPs|DNS|MTU|Table|PreUp|PostUp|PreDown|PostDown|PersistentKeepalive)' "$conf" \
    | grep -v -E '^[Mm][Tt][Uu]' > "$tmp" || true

  if [ -n "$ipv4" ]; then
    sed -i "/\[Interface\]/a Address = ${ipv4}" "$tmp"
  fi
  sed -i "/\[Interface\]/a MTU = ${MTU}" "$tmp"

  if ! grep -q '^\[Peer\]' "$tmp"; then
    err "no [Peer] in $conf"
    rm -f "$tmp"
    return 1
  fi
  sed -i "/\[Peer\]/a AllowedIPs = 0.0.0.0/0" "$tmp"
  sed -i "/\[Peer\]/a PersistentKeepalive = 15" "$tmp"

  if [ -n "$ENDPOINT_IP" ]; then
    if grep -q '^Endpoint' "$tmp"; then
      sed -i "s|^Endpoint.*|Endpoint = ${ENDPOINT_IP}|" "$tmp"
    else
      sed -i "/\[Peer\]/a Endpoint = ${ENDPOINT_IP}" "$tmp"
    fi
  fi

  mv "$tmp" "$conf"
}

write_wireproxy_conf() {
  local id="$1"
  local dir port conf
  dir="$(instance_dir "$id")"
  port="$(instance_port "$id")"
  conf="${dir}/wireproxy.conf"
  cat > "$conf" <<EOF
# generated by warp-pool — do not edit by hand
WGConfig = ${dir}/wgcf-profile.conf

[Socks5]
BindAddress = 0.0.0.0:${port}
EOF
}

write_meta() {
  local id="$1"
  local dir meta
  dir="$(instance_dir "$id")"
  meta="${dir}/meta.json"
  local port healthy exit_ip failures last_rotate pid
  port="$(instance_port "$id")"
  healthy="${2:-false}"
  exit_ip="${3:-}"
  failures="${4:-0}"
  last_rotate="${5:-}"
  pid="${6:-}"
  if [ -z "$last_rotate" ] && [ -f "$meta" ]; then
    last_rotate="$(jq -r '.last_rotate // empty' "$meta" 2>/dev/null || true)"
  fi
  jq -n \
    --argjson id "$id" \
    --argjson port "$port" \
    --argjson healthy "$healthy" \
    --arg exit_ip "$exit_ip" \
    --argjson failures "$failures" \
    --arg last_rotate "$last_rotate" \
    --arg pid "$pid" \
    '{id:$id, port:$port, healthy:$healthy, exit_ip:$exit_ip, failures:$failures, last_rotate:$last_rotate, pid:$pid}' \
    > "$meta"
}

probe_instance() {
  local id="$1"
  local port trace
  port="$(instance_port "$id")"
  trace="$(curl -fsS --max-time "${HEALTH_TIMEOUT:-10}" \
    --socks5-hostname "127.0.0.1:${port}" \
    "https://cloudflare.com/cdn-cgi/trace" 2>/dev/null || true)"
  if echo "$trace" | grep -qE 'warp=(on|plus)'; then
    local ip
    ip="$(echo "$trace" | grep -E '^ip=' | cut -d= -f2- || true)"
    echo "$ip"
    return 0
  fi
  return 1
}
