#!/usr/bin/env bash
# shared helpers for warp-pool
set -euo pipefail

DATA_DIR="${DATA_DIR:-/data}"
INSTANCE_PORT_BASE="${INSTANCE_PORT_BASE:-11000}"
MTU="${MTU:-1280}"
ENDPOINT_IP="${ENDPOINT_IP:-}"
SCRIPTS_DIR="${SCRIPTS_DIR:-/opt/warp-pool/scripts}"
PID_DIR="${PID_DIR:-/run/warp-pool}"

log() { echo "==> [warp-pool] $*"; }
err() { echo "==> [warp-pool][ERROR] $*" >&2; }

instance_dir() {
  echo "${DATA_DIR}/instances/$1"
}

instance_port() {
  local id="$1"
  echo $((INSTANCE_PORT_BASE + id))
}

ensure_dirs() {
  local id="$1"
  mkdir -p "$(instance_dir "$id")" "${DATA_DIR}/state" "${PID_DIR}"
}

# Sanitize wgcf profile for wireproxy (IPv4-focused, MTU, keepalive, endpoint)
# Portable: no GNU sed append (BusyBox breaks on /a).
sanitize_wgconf() {
  local conf="$1"
  local tmp ipv4 endpoint_line privkey pubkey
  tmp="$(mktemp)"

  ipv4="$(grep -E '^Address' "$conf" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}' | head -n1 || true)"
  privkey="$(grep -E '^PrivateKey' "$conf" | head -n1 | sed 's/^PrivateKey\s*=\s*//')"
  pubkey="$(grep -E '^PublicKey' "$conf" | head -n1 | sed 's/^PublicKey\s*=\s*//')"
  endpoint_line="$(grep -E '^Endpoint' "$conf" | head -n1 || true)"
  if [ -n "$ENDPOINT_IP" ]; then
    # keep port from original endpoint if present
    local port
    port="$(echo "$endpoint_line" | sed -n 's/.*:\([0-9]\+\).*/\1/p')"
    port="${port:-2408}"
    endpoint_line="Endpoint = ${ENDPOINT_IP}:${port}"
  fi

  if [ -z "$ipv4" ] || [ -z "$privkey" ] || [ -z "$pubkey" ] || [ -z "$endpoint_line" ]; then
    err "sanitize: missing required fields in $conf"
    rm -f "$tmp"
    return 1
  fi

  cat > "$tmp" <<EOF
[Interface]
PrivateKey = ${privkey}
Address = ${ipv4}
MTU = ${MTU}

[Peer]
PublicKey = ${pubkey}
Endpoint = $(echo "$endpoint_line" | sed 's/^Endpoint\s*=\s*//')
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 15
EOF

  mv "$tmp" "$conf"
}

write_wireproxy_conf() {
  local id="$1"
  local dir port conf
  dir="$(instance_dir "$id")"
  port="$(instance_port "$id")"
  conf="${dir}/wireproxy.conf"
  cat > "$conf" <<EOF
# generated by warp-pool — do not edit by hand
WGConfig = ${dir}/wgcf-profile.conf

[Socks5]
BindAddress = 0.0.0.0:${port}
EOF
}

write_meta() {
  local id="$1"
  local dir meta
  dir="$(instance_dir "$id")"
  meta="${dir}/meta.json"
  local port healthy exit_ip failures last_rotate pid
  port="$(instance_port "$id")"
  healthy="${2:-false}"
  exit_ip="${3:-}"
  failures="${4:-0}"
  last_rotate="${5:-}"
  pid="${6:-}"
  if [ -z "$last_rotate" ] && [ -f "$meta" ]; then
    last_rotate="$(jq -r '.last_rotate // empty' "$meta" 2>/dev/null || true)"
  fi
  jq -n \
    --argjson id "$id" \
    --argjson port "$port" \
    --argjson healthy "$healthy" \
    --arg exit_ip "$exit_ip" \
    --argjson failures "$failures" \
    --arg last_rotate "$last_rotate" \
    --arg pid "$pid" \
    '{id:$id, port:$port, healthy:$healthy, exit_ip:$exit_ip, failures:$failures, last_rotate:$last_rotate, pid:$pid}' \
    > "$meta"
}

probe_instance() {
  local id="$1"
  local port trace
  port="$(instance_port "$id")"
  trace="$(curl -fsS --max-time "${HEALTH_TIMEOUT:-10}" \
    --socks5-hostname "127.0.0.1:${port}" \
    "https://cloudflare.com/cdn-cgi/trace" 2>/dev/null || true)"
  if echo "$trace" | grep -qE 'warp=(on|plus)'; then
    local ip
    ip="$(echo "$trace" | grep -E '^ip=' | cut -d= -f2- || true)"
    echo "$ip"
    return 0
  fi
  return 1
}
